# Generated by Django 4.2.2 on 2023-10-18 06:06

import appSite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowHostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255, unique=True, validators=[appSite.models.validate_ip], verbose_name='IP')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='AlterDatetime')),
            ],
            options={
                'verbose_name': '1. AllowHost',
                'verbose_name_plural': '1. AllowHost',
            },
        ),
        migrations.CreateModel(
            name='SenderLogManagerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_log', models.PositiveIntegerField(choices=[(0, 'N0'), (1, 'YES')], default=0, verbose_name='USE LOG')),
            ],
            options={
                'verbose_name': '2. SenderLogManager',
                'verbose_name_plural': '2. SenderLogManager',
            },
        ),
        migrations.CreateModel(
            name='SenderLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255, verbose_name='Customer IP')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Datetime')),
                ('status', models.IntegerField(choices=[(1, 'SUCCEED'), (0, 'FAIL')], default=1, verbose_name='Status')),
                ('error_msg', models.TextField(blank=True, default='', null=True, verbose_name='Error Msg')),
            ],
            options={
                'verbose_name': '3. SenderLogDetail',
                'verbose_name_plural': '3. SenderLogDetail',
            },
        ),
    ]
